services:
  - type: web
    name: cepv-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cepv_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cepv_backend.settings
